### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by darkphoenix** [dcritch/assg#1]
Hello,
I'm using an improved version of this role to generate my own static site, however I don't feel legally safe to share that code because this repository does not have any license.  Would you mind adding a LICENSE.md to it?
(I personally don't much care which license specifically, I tend to use permissive licenses like MIT or BSD myself but I'd be fine with a GPL or similar, too)

**Comment by dcritch** [comment]
No problem. Happy to hear someone found this useful!
